// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1olKL99I_mV7pbmldR2nF4k8WkD_v8XU',
    appId: '1:468307143948:web:5ef3b0a309fe123b2c2d29',
    messagingSenderId: '468307143948',
    projectId: 'yonima-8b9af',
    authDomain: 'yonima-8b9af.firebaseapp.com',
    storageBucket: 'yonima-8b9af.firebasestorage.app',
    measurementId: 'G-2JHG0FQ79X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6SYwaogNfyzUaWCQYRFPGMDAfecYnVSc',
    appId: '1:468307143948:android:041a8710669187f32c2d29',
    messagingSenderId: '468307143948',
    projectId: 'yonima-8b9af',
    storageBucket: 'yonima-8b9af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZm356wknKeJCBv2aCkfcKK4Q8cvybY5A',
    appId: '1:468307143948:ios:1f33303661dfa0422c2d29',
    messagingSenderId: '468307143948',
    projectId: 'yonima-8b9af',
    storageBucket: 'yonima-8b9af.firebasestorage.app',
    androidClientId: '468307143948-2grrmhu807dhmcqs9r64868n9jtsvbt1.apps.googleusercontent.com',
    iosBundleId: 'com.agripas.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZm356wknKeJCBv2aCkfcKK4Q8cvybY5A',
    appId: '1:468307143948:ios:1f33303661dfa0422c2d29',
    messagingSenderId: '468307143948',
    projectId: 'yonima-8b9af',
    storageBucket: 'yonima-8b9af.firebasestorage.app',
    androidClientId: '468307143948-2grrmhu807dhmcqs9r64868n9jtsvbt1.apps.googleusercontent.com',
    iosBundleId: 'com.agripas.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAog3aTLcwIUZnfJpT9Tz8vnwL9KXG1Lsw',
    appId: '1:468307143948:web:ee8d3e04a0d7b74e2c2d29',
    messagingSenderId: '468307143948',
    projectId: 'yonima-8b9af',
    authDomain: 'yonima-8b9af.firebaseapp.com',
    storageBucket: 'yonima-8b9af.firebasestorage.app',
    measurementId: 'G-H4Z99WG0MP',
  );
}
